### ISSUE TITLE
Choose front/back camera

### ISSUE THREAD

**Issue by IamChrister** [yasirkula/UnityNativeCamera#26] opened 2019-09-25 05:27 UTC
Hi,

I just noticed that using TakePicture() once opened the front camera on Galaxy S8. Every other time it has defaulted to the back camera so it felt a little bit weird. Is there a way to control or force the plugin to use the back camera?

From another issue it appeared that back camera should be the default so I'm not sure why it opened the front cam. For my application it is critical that the back camera is used and not the front.

Thanks for the repo!

**Comment by yasirkula** [comment] 2019-09-25 17:56
I'll try to resolve this issue using this method: https://github.com/jamesmontemagno/MediaPlugin/issues/307#issuecomment-356199135

**Comment by yasirkula** [comment] 2019-09-29 12:32
Duplicate of #6

**Closed by yasirkula** 2019-09-29 12:32 UTC

**Comment by yasirkula** [comment] 2019-09-29 15:05
I've added PreferredCamera parameter in https://github.com/yasirkula/UnityNativeCamera/commit/a070c0a0b7648116e69e3723a500b674665ce6a2. Can you please check out the latest release and see if it works?

**Comment by Imagine-Devin118** [comment] 2020-01-20 07:16
It doesn't seem to work on Samsung S8+, and it always uses the system default settings

**Comment by yasirkula** [comment] 2020-01-20 16:12
Yes, not all camera apps (including built-in ones) respect the passed parameters. Android OS doesn't enforce camera apps to respect any of the passed parameters, thus we see all sorts of different behaviours across different camera apps.
