### ISSUE TITLE
Force native camera to open up in 1:1 square box

### ISSUE THREAD

**Issue by adityathoutam** [yasirkula/UnityNativeCamera#42] opened 2020-08-04 10:44 UTC
Can I force native camera to open in square mode by default?

**Comment by yasirkula** [comment] 2020-08-04 11:24
I haven't seen this feature in native functions, I don't think it is possible.

**Comment by yasirkula** [comment] 2020-12-07 18:29
Duplicate of #38

**Closed by yasirkula** 2020-12-07 18:29 UTC
